# Generated by Django 2.1.6 on 2019-09-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='/home/hasime/Desktop/dev/HappinessGuru/static/media', path='/home/hasime/Desktop/dev/HappinessGuru/static/media')),
            ],
        ),
    ]
