# Generated by Django 2.1.12 on 2019-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='path',
        ),
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test/'),
        ),
    ]
